### ISSUE TITLE
Building a shared library

### ISSUE THREAD

**Issue by j-haj** [alexcrichton/cc-rs#250]
It seems that `cc` offers the ability to build a shared object via the `.shared(true)` method, but this object is then statically linked into the rust executable. Additionally, by default on macOS (which uses `gcc` as an alias for `clang`), the use of the `.shared(true)` method doesn't actually do anything because `clang` doesn't recognize `-shared` as a valid flag when creating an object file. As far as I can tell, there does not seem to be a way to build a shared library and then link it with the rust executable with this crate.

This seems to be confirmed [here](https://github.com/alexcrichton/cc-rs/blob/7b243497284095dae5e4d3d8a0387226ee9b51c4/src/lib.rs#L1157) where `cc` is always using `ar`, rather than the necessary `ld` for shared libraries.

Is there something I'm missing? If not I think this would be useful functionality.

**Comment by alexcrichton** [comment]
IIRC that flag was added to fix a bug but didn't actually end up fixing the bug or wasn't needed. In general though it's not the intention of this crate to produce shared libraries, just static libraries.

**Comment by tjpalmer** [comment]
I understand the current intent of this library. I think there could be value in expanding the scope to building shared libraries and executables. I suggest this because it could be useful for other needs, and you've already done some good legwork here (like the windows registry, for example) that others would need to duplicate.

For my current needs (building a different language at runtime to c/c++, but others could have other situations), it seems like another alternative is for me to expect cmake to do this work instead.

Could you consider expanding the scope even just a little for now, or would you recommend relying on cmake?

Or I guess another alternative is compile to rust with c included there ...

**Comment by alexcrichton** [comment]
Unfortunately everything to do with shared libraries, loading, and copying them around I do not have time to review or maintain. I'd prefer to keep this library as simple as possible and targeted towards just "getting C into Rust" which 99% of the time doesn't require shared libraries. I think that this function should likely be built on top of `cc-rs`, if at all.

**Comment by tjpalmer** [comment]
Thanks for the feedback. I think I'll just start from this project as a base for getting what I need done. Thanks for your hard work!

**Comment by alexcrichton** [comment]
I'm going to close this because I would prefer to not support building a shared library with this crate. It'd be neat to see if a crate could be made which depends on `cc` which does support this though!

**Comment by Jakobeha** [comment]
For people who are still interested in building shared libraries, at least on macOS you just have to run `clang -dynamiclib -o libfoobar.dylib <object files produced during compilation>`.

e.g.

```rust
let status = Command::new("/usr/bin/clang")
        .args(["-dynamiclib", "-o", "libfoobar.dylib"])
        .args(find_object_files_in("."))
        .status()
        .expect("link command failed, IO error");
if !status.success() {
    panic!("link command failed, exit status {}", status);
}
```

Pass `-undefined dynamic_lookup` if your shared library references other shared symbols
