### ISSUE TITLE
cannot find -l<lib>

### ISSUE THREAD

**Issue by hajsf** [alexcrichton/cc-rs#362]
I've an issue with [sqlite3-src](https://github.com/stainless-steel/sqlite3-src/blob/master/Cargo.toml) that is depending on your lib, so, I may find the answer with you.

I'm using `macOS`, and trying to compile for `Android` using the command
```bash
cargo build --target x86_64-linux-android --release
```

I got the error while compiling the [rusqlite](https://github.com/jgallagher/rusqlite) which is depending on your library

> = note: /Users/../NDK/x86_64/bin/../lib/gcc/x86_64-linux-android/4.9.x/../../../../x86_64-linux-android/bin/ld: error: cannot find -lsqlite3
> clang70: error: linker command failed with exit code 1 (use -v to see invocation)                        

I already have sqlite3 installed:
```bash
Hasans-Air:~ h_ajsf$ brew install sqlite
Warning: sqlite 3.26.0 is already installed and up-to-date
To reinstall 3.26.0, run `brew reinstall sqlite`
```

And it compiled smoothly for mac lib, using
```bash
cargo build --release
``` 

I posted this at the [forum](https://users.rust-lang.org/t/linker-cannot-find-lsqlite3/23230) as well with some trials, but nothing work :(

**Comment by alexcrichton** [comment]
Thanks for the report! The issue here isn't actually with this library and is in the local configuration. You're doing a cross-compile but the sqlite installed is not compiled for Android, but rather OSX. You'll want to compile sqlite3 for Android or file an upstream bug report with the sqlite3 crate to compile sqlite3 from source
