### ISSUE TITLE
Allow to skip the automatic addition of compiler flags

### ISSUE THREAD

**Issue by glandium** [alexcrichton/cc-rs#371]
External build systems like Firefox's may want to pass down its own flags for target, arch, ABI and more, and all they can do at the moment is pass CFLAGS/CXXFLAGS, but then cc-rs goes on to add its own flags after those, which may override what the explicit CFLAGS/CXXFLAGS wanted. One example is that we're passing the correct target flags for clang-cl, but cc-rs was adding -m32 for --target aarch64-windows-msvc, effectively making it a 32-bits arm build (which failed in some ucrt header complaining that ARM desktop builds are not allowed). Some other flags that have an impact on ABI (fpu, etc.) could be at odds with what the top-level build system really wants.
So I think it should be possible to bypass the entire section that deals with adding platform-specific flags .

**Comment by alexcrichton** [comment]
I think we could go either way on this because the `cc` crate shouldn't add any flags that actually conflict with other flags, modulo bugs. It's a bug that `-m32` was passed for MSVC as this crate only handled x86 and x86_64 there.

This could be useful as a bug prevention mechanism but this crate is already *very* carefully constructed and complicated, so I'd sort of prefer that it sticks to passing a minimal set of working flags and then fix bugs as they arise.

**Comment by alexcrichton** [comment]
> that are added and are at odds with what we'd actually want for Firefox

I think in that case you want a different target. The purpose of the `-march` style flags is to match the Rust code. If you want different flags, then you likely want to compile the Rust code differently.

> As a matter of fact, the flags that cc-rs adds are also at odds with how rust's target itself might be configured through -C target_feature.

Yes and there's various bugs open to read flags like this and process them in `cc`. It's obviously a nontrivial undertaking. That's where I think an escape hatch can possibly work, but I think it's worthwhile to acknowledge it's a hack of an escape hatch that should not be necessary, it's only because work isn't being diverted elsewhere.

**Comment by GeorgeHahn** [comment]
This should be fixed in version 1.0.30 - the presence of `-m` flags in `CFLAGS/CXXFLAGS` will automatically disable the default flags. If this is insufficient, the environment variable `CRATE_CC_NO_DEFAULTS` may be set to manually disable default flags.

**Comment by alexcrichton** [comment]
I'm going to close this since various changes have happened internally here and for entirely skipping flags compilation can always be done in build scripts themselves instead of using this crate.
