### ISSUE TITLE
Support wasm32-unknown-unknown

### ISSUE THREAD

**Issue by pravdomil** [alexcrichton/cc-rs#378]
Now I see only support for `emscripten`, is there any plan for supporting target `wasm32-unknown-unknown`?

https://github.com/alexcrichton/cc-rs/blob/9e57a2b0e922a96be5d28b1adf6e5fc41d5d762c/src/lib.rs#L1696

**Comment by alexcrichton** [comment]
Ideally we would support this! The target, however, doesn't really have a C compiler because there's no real standard "sysroot" (currently) to actually compile C code against. The recently released `clang` 8.0 compiler though is the only one we'd also be compatible with on wasm32-unknown-unknown, so we could at least add that and rely on users to set the right CFLAGS to compile with the right headers/sysroot/etc

**Comment by pravdomil** [comment]
I'll be happy to use `clang` 8 for it.

**Comment by tanis2000** [comment]
I'm facing a similar problem here https://github.com/servo/rust-stb-image/issues/94 but I have no clue where the wasm32 sysroot lives. I'm on CLANG 8.0.0 so I suppose it actually supports compiling to wasm32 but without the correct sysroot it can't find stdio.h and such headers.
