### ISSUE TITLE
Crosscompile for i686

### ISSUE THREAD

**Issue by siscia** [alexcrichton/cc-rs#469]
I post here, I don't believe it is really an issue or that we can do much about it, but it may help somebody else.

To crosscompile for i686 on ubuntu I did the following.

1. Install `linux-libc-dev-i386-cross` 
1. Make sure that `cc` point to `gcc` using: `sudo update-alternatives --config cc`
2. Create the i686-linux-gnueabi-gcc compiler with `sudo ln -s /usr/bin/gcc /usr/bin/i686-linux-gnueabi-gcc`
3. Set `export $CROSS_COMPILE="i686-linux-gnueabi-"`
4. Set `export $ARCH="i686"`
3. Added:
```
+        .include("/usr/i686-linux-gnu/include/")
+        .include("/usr/i686-linux-gnu/include/asm/")
+        .include("/usr/i686-linux-gnu/include/asm-generic/")
```

After this the crosscompilation complete.

Cheers,

**Comment by alexcrichton** [comment]
Thanks for the report! Typically though this is taken care of by selecting the right compiler rather than adding manual include paths. This crate has a lot of various options used to select the compiler, but beyond that I don't think it'll be including anything like adding include paths automatically.
