### ISSUE TITLE
Support executable compilation

### ISSUE THREAD

**Issue by sfackler** [alexcrichton/cc-rs#63]
A common configuration error when using rust-openssl is to reference headers and libraries from different versions which results in weird and hard to track down breakage. I want to handle this by compiling and running a little executable that compares the values of the version encoded in a `#define` in the headers and a function in the library.

Unfortunately, gcc-rs will currently only build staticlibs.

**Comment by alexcrichton** [comment]
This is actually pretty intentional today because it's not often possible to actually run the executable that would be generated (e.g. almost all cross compilation scenarios).

The "most robust" thing I think would perhaps be something like `gcc -E` and then parsing the output if you just want to learn about various `#define` constants.

**Comment by sfackler** [comment]
That's a fair point, but the check I want to make isn't necessary for compilation to continue, and since the *vast* majority of compilation is not crossed I'm fine with gcc-rs saying "no".

The `gcc -E` approach isn't going to work because I need one #define out of a header and the result of calling `SSLeay()` at runtime.

**Comment by alexcrichton** [comment]
So this is one reason I added the [`get_compiler` API](http://alexcrichton.com/gcc-rs/gcc/struct.Config.html#method.get_compiler) where you could get the tool itself and add your own arguments and such, perhaps that would be good enough for now rather than adding a first-class API?

**Comment by AndiDog** [comment]
I also just wanted to suggest this feature. If you think cross-compilation is really a problem, you could offer the API to only compile executables to the host architecture (not to the cross-compiled architecture), which is the exact use case of @sfackler and me (dynamic build configuration).

**Comment by alexcrichton** [comment]
I'm going to close this as it's not currently my intention to support this in this library as this crate is primarily for build scrips and building native code, especially handling the cross-compile cases.

**Comment by quadrupleslap** [comment]
Very niche use-case, but I'm pretty sure generating executables would be very useful for my build script - I need to generate a second executable to be called by the Chromium Embedded Framework on the target platform.

**Comment by quadrupleslap** [comment]
Does this work across platforms though? I'm not getting any target triples.

```rust
let mut cc = cc::Build::new();
let mut cmd = cc.get_compiler().to_command();
cmd.arg("test.c");
assert!(cmd.status().unwrap().success());
```

**Comment by BenLeadbetter** [comment]
Seems like an obvious missing feature to me. How else would one support unit test executables for C/C++ libraries built with `cc` ?

Best solution I could come up with is a [pretty ugly workaround](https://github.com/BenLeadbetter/ygglet/blob/98753c888e2dc764f81625aef3e127f8d5214168/engine/build.rs#L48-L98).

**Comment by madsmtm** [comment]
> Seems like an obvious missing feature to me. How else would one support unit test executables for C/C++ libraries built with `cc` ?

You wouldn't (or you'd build the feature upon `cc-rs` yourself, as you've done).

The problem is that building executables, just like building shared libraries (see e.g. https://github.com/rust-lang/cc-rs/pull/1582), requires invoking the linker. And the linker is like a whole separate program with its own slew of configuration flags and requirements, it's a deep rabbit hole that we don't want `cc-rs` to go down into.

Someone could make a `ld-rs` for this use-case, but it's not in scope for `cc-rs`.
